steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/build-7.0', '--build-arg=PHP_IMAGE=php:7.0-stretch', '.' ]
  waitFor: ['-']
  id: 'build-7.0'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/build-7.1', '--build-arg=PHP_IMAGE=php:7.1-stretch', '.' ]
  waitFor: ['-']
  id: 'build-7.1'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/build-7.2', '--build-arg=PHP_IMAGE=php:7.2-stretch', '.' ]
  waitFor: ['-']
  id: 'build-7.2'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/build-7.3', '--build-arg=PHP_IMAGE=php:7.3-stretch', '.' ]
  waitFor: ['-']
  id: 'build-7.3'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/build-7.4', '--build-arg=PHP_IMAGE=php:7.4-buster', '.' ]
  waitFor: ['-']
  id: 'build-7.4'

- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'gcr.io/$PROJECT_ID/build-7.0']
  waitFor: ['build-7.0']
  id: 'run-7.0'
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'gcr.io/$PROJECT_ID/build-7.1']
  waitFor: ['build-7.1']
  id: 'run-7.1'
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'gcr.io/$PROJECT_ID/build-7.2']
  waitFor: ['build-7.2']
  id: 'run-7.2'
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'gcr.io/$PROJECT_ID/build-7.3']
  waitFor: ['build-7.3']
  id: 'run-7.3'
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'gcr.io/$PROJECT_ID/build-7.4']
  waitFor: ['build-7.4']
  id: 'run-7.4'
images: [
 'gcr.io/$PROJECT_ID/build-7.0',
 'gcr.io/$PROJECT_ID/build-7.1',
 'gcr.io/$PROJECT_ID/build-7.2',
 'gcr.io/$PROJECT_ID/build-7.3',
 'gcr.io/$PROJECT_ID/build-7.4'
]
